In [2]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import os

Plotting all:

In [88]:
files = list(os.listdir('./lab_data/'))
files.sort()


In [62]:
for i in range(len(files)):
    data = pd.read_csv('./lab_data/{}'.format(files[i]), header=1, delimiter='\t')
    old_cols = data.columns.tolist()
    data = data.rename(columns={old_cols[0]:'Position', old_cols[1]:'Intensity'})
    # moving average
    data["MA"] = data["Intensity"].rolling(window=150, center=True).mean()
    ax = plt.gca()
    plt.plot(data['Position'], data['Intensity'])
    plt.plot(data['Position'], data['MA'])
    ax.set(xlabel=old_cols[0], ylabel=old_cols[1], title=files[i])
    plt.savefig('./plotted/'+files[i]+'.png', dpi=350)
    plt.clf()

<Figure size 432x288 with 0 Axes>

Plotting Single Slit 

In [77]:
data = pd.read_csv('./lab_data/BEECH7.txt', header=1, delimiter='\t')
old_cols = data.columns.tolist()
winy=150
data = data.rename(columns={old_cols[0]:'Position', old_cols[1]:'Intensity'})
data['MA'] = data['Intensity'].rolling(window=winy, center=True).mean()
old_data = data.copy()
data = data.fillna(-1111111)
max(data['MA'])

0.30328086666666665

In [78]:
maxframe = data.loc[(data['Position'] >= -.05) & (data['Position'] <= -.03)]
maxy = max(maxframe['MA'])
max_row = data.loc[data['MA'] == maxy]
max_pos = float(max_row['Position'])
minframe = data.loc[(data['Position'] >= -.03) & (data['Position'] <= -.01)]
miny = min(minframe['MA'])
min_row = data.loc[data['MA'] == miny]
min_pos = float(min_row['Position'])
diff = abs(abs(max_pos)-abs(min_pos))
data['MA'] = old_data['MA']

In [87]:
ax = plt.gca()
plt.plot(data['Position'], data['Intensity'], label='Raw data at gain=100')
plt.plot(data['Position'], data['MA'], label='Rolling average window={}'.format(winy))
# plotting important points
plt.plot(max_pos, maxy, 'mo', label='Maxima')
plt.plot(min_pos, miny, 'ro', label='Minima')
ax.set(xlabel=old_cols[0], ylabel=old_cols[1], title='0.04mm Single Slit, dist={}m'.format(round(diff, 7)))
ax.legend()
#ax.legend('Raw data, gain=100', 'Rolling average='.format(winy), 'Max and min')
plt.savefig('./important_bois/'+'BEECH7'+'.png', dpi=350)
plt.clf()

<Figure size 432x288 with 0 Axes>

Plotting Double Slit a=.04mm, d=.5mm

In [121]:
# HANGRY
data = pd.read_csv('./lab_data/HANGRY1.txt', header=1, delimiter='\t')
old_cols = data.columns.tolist()
winy=250
data = data.rename(columns={old_cols[0]:'Position', old_cols[1]:'Intensity'})
data['MA'] = data['Intensity'].rolling(window=winy, center=True).mean()
old_data = data.copy()
data = data.fillna(-1111111)

In [141]:
#rows = data.loc[(data['Position']>=.005) & (data['Position']<=.007)]
maxes = []
for i in range(5):
    if i == 0:
        min_val = .005
    else:
        min_val = maxes[i-1][1]
    maxes.append(max_finder42069(min_val, data))
maxes = np.asarray(maxes)
maxes
dists = abs(maxes[0, 1] - maxes[1:, 1])
dists

array([0.00022, 0.0005 , 0.00072, 0.00094])

In [170]:
def max_finder42069(min_val, data):
    rows = data.loc[(data['Position']>min_val) & (data['Position']<=.008)]
    one_max = max(rows['Intensity'])
    one_max_pos = float(rows[rows['Intensity'] == one_max]['Position'])
    return (one_max, one_max_pos)

In [150]:
data['MA'] = old_data['MA']
ax = plt.gca()
plt.plot(data['Position'], data['Intensity'], label='Raw data at gain=10')
plt.plot(data['Position'], data['MA'], label='Rolling average window={}'.format(winy))
plt.plot(maxes[:, 1], maxes[:, 0], 'ro', label='Maximae')
# plotting important points
#plt.plot(max_pos, maxy, 'mo', label='Maxima')
#plt.plot(min_pos, miny, 'ro', label='Minima')
ax.set(xlabel=old_cols[0], ylabel=old_cols[1], title='Dbl Slit a=.04mm, d=.5mm, dist={}m'.format(dists))
ax.legend(bbox_to_anchor = [.6, 1])
#ax.legend('Raw data, gain=100', 'Rolling average='.format(winy), 'Max and min')

plt.savefig('./important_bois/'+'HANGRY1'+'.png', dpi=350, bbox_inches='tight')
plt.clf()

<Figure size 432x288 with 0 Axes>

Plotting THICC1, a=.08mm, d=.5mm

In [171]:
# THICC1
data = pd.read_csv('./lab_data/THICC1.txt', header=1, delimiter='\t')
old_cols = data.columns.tolist()
winy=250
data = data.rename(columns={old_cols[0]:'Position', old_cols[1]:'Intensity'})
data['MA'] = data['Intensity'].rolling(window=winy, center=True).mean()
old_data = data.copy()
data = data.fillna(-1111111)

In [172]:
maxes = []
for i in range(5):
    if i == 0:
        min_val = -.0055
    else:
        min_val = maxes[i-1][1]+.0001
    maxes.append(max_finder42069(min_val, data))
maxes = np.asarray(maxes)
maxes
dists = abs(maxes[0, 1] - maxes[1:, 1])
dists

array([0.00028, 0.0005 , 0.00072, 0.00095])

In [173]:
data['MA'] = old_data['MA']
ax = plt.gca()
plt.plot(data['Position'], data['Intensity'], label='Raw data at gain=10')
plt.plot(data['Position'], data['MA'], label='Rolling average window={}'.format(winy))
plt.plot(maxes[:, 1], maxes[:, 0], 'ro', label='Maximae')
# plotting important points
#plt.plot(max_pos, maxy, 'mo', label='Maxima')
#plt.plot(min_pos, miny, 'ro', label='Minima')
ax.set(xlabel=old_cols[0], ylabel=old_cols[1], title='Dbl Slit a=.08mm, d=.5mm, dist={}m'.format(dists))
ax.legend(bbox_to_anchor = [.6, 1])
#ax.legend('Raw data, gain=100', 'Rolling average='.format(winy), 'Max and min')

plt.savefig('./important_bois/'+'THICC1'+'.png', dpi=350, bbox_inches='tight')
plt.clf()

<Figure size 432x288 with 0 Axes>

Plant a=.04mm, d=.25mm

In [176]:
# PLANT1
data = pd.read_csv('./lab_data/PLANT1.txt', header=1, delimiter='\t')
old_cols = data.columns.tolist()
winy=350
data = data.rename(columns={old_cols[0]:'Position', old_cols[1]:'Intensity'})
data['MA'] = data['Intensity'].rolling(window=winy, center=True).mean()
old_data = data.copy()
data = data.fillna(-1111111)

In [177]:
maxes = []
for i in range(5):
    if i == 0:
        min_val = -.0055
    else:
        min_val = maxes[i-1][1]+.00015
    maxes.append(max_finder42069(min_val, data))
maxes = np.asarray(maxes)
maxes
dists = abs(maxes[0, 1] - maxes[1:, 1])
dists

array([0.00039, 0.00078, 0.00117, 0.00156])

In [178]:
data['MA'] = old_data['MA']
ax = plt.gca()
plt.plot(data['Position'], data['Intensity'], label='Raw data at gain=10')
plt.plot(data['Position'], data['MA'], label='Rolling average window={}'.format(winy))
plt.plot(maxes[:, 1], maxes[:, 0], 'ro', label='Maximae')
# plotting important points
#plt.plot(max_pos, maxy, 'mo', label='Maxima')
#plt.plot(min_pos, miny, 'ro', label='Minima')
ax.set(xlabel=old_cols[0], ylabel=old_cols[1], title='Dbl Slit a=.04mm, d=.25mm, dist={}m'.format(dists))
ax.legend(bbox_to_anchor = [.6, 1])
#ax.legend('Raw data, gain=100', 'Rolling average='.format(winy), 'Max and min')

plt.savefig('./important_bois/'+'PLANT1'+'.png', dpi=350, bbox_inches='tight')
plt.clf()

<Figure size 432x288 with 0 Axes>